package com.renobile.carrinho.util

const val PREF_DEVICE_ID = "DeviceId2"
const val PREF_FCM_TOKEN = "PrefFcmToken"
const val PREF_SHARE_LINK = "PrefStoreLink"
const val PREF_COMMENTS = "PrefComments"
const val PREF_HAVE_PLAN = "PrefHavePlan"
const val PREF_APP_NAME = "PrefAppName"
const val PREF_BILL_PLAN_YEAR = "PrefBillPlanYear"
const val PREF_USER_NAME = "PrefUserName"
const val PREF_USER_EMAIL = "PrefUserEmail"
const val PREF_NOTIFICATION_JSON = "PrefNotificationJson"
const val PREF_PRICE_FIRST = "PrefPriceFirst"
const val PREF_SIZE_FIRST = "PrefSizeFirst"
const val PREF_PRICE_SECOND = "PrefPriceSecond"
const val PREF_SIZE_SECOND = "PrefSizeSecond"
const val PREF_PLAN_VIDEO_DURATION = "PrefPlanVideoDuration"
const val PREF_PLAN_VIDEO_MILLIS = "PrefPlanVideoMillis"

const val PREF_ADMOB_ID = "PrefAdMobId"
const val PREF_ADMOB_AD_MAIN_ID = "PrefAdMobAdMainId"
const val PREF_ADMOB_INTERSTITIAL_ID = "PrefAdMobInterstitialId"
const val PREF_ADMOB_REMOVE_ADS_ID = "PrefAdMobRemoveAds"
const val PREF_ADMOB_OPEN_APP_ID = "PrefAdMobOpenAppId"
