default_platform(:android)

platform :android do
  desc "Build the release AAB and upload it to Google Play"
  lane :upload do |options|
    gradle(task: "bundleRelease")
    supply(
      package_name: "com.renobile.carrinho",
      track: options[:track] || "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )
  end
end
